### ISSUE TITLE
Duplicate code DwUsbHostDxe

### ISSUE THREAD

**Issue by mrmajik45** [andreiw/RaspberryPiPkg#69] opened 2018-09-17 15:20 UTC
Found in:
Drivers\DwUsbHostDxe\DwUsbHostDxe.c:684-693
Drivers\DwUsbHostDxe\DwUsbHostDxe.c:737-746

**Comment by andreiw** [comment] 2018-09-18 03:40
It's similar, and some places may be questionable (EfiUsbPortReset for example), but it's not duplicate. One sets features. Another clears. I'm closing this as a not a bug at the moment although cleanup may be desired at some point.

**Closed by andreiw** 2018-09-18 03:40 UTC
