### ISSUE TITLE
Very Slow Clock Ticks

### ISSUE THREAD

**Issue by gordan-bobic** [andreiw/RaspberryPiPkg#3] opened 2018-01-04 19:06 UTC
It looks like the timer countdown in grub is very slow after being booted by this build of Tianocore. It takes 2-3 seconds to tick down by 1 second on the boot menu screen.

**Comment by andreiw** [comment] 2018-01-13 20:51
I can't confirm this with either the tickdown in the UEFI Shell, or the openSUSE grub. I tested the two RPi3s I have, both with and without serial.

Try one of my prebuilts and let me know.

**Comment by andreiw** [comment] 2018-01-21 15:34
Okay, closing as no repro

**Comment by andreiw** [comment] 2018-02-22 10:55
This was likely caused by USB error spew in early split transfer code, due to an unsupported keyboard attached. Serial logs would have helped. Issue should be resolved now.

**Closed by andreiw** 2018-02-22 10:55 UTC
Labels: invalid
